/***************************************************************************
 *   Copyright (C) 2009 by Dario Freddi                                    *
 *   drf@chakra-project.org                                                *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.          *
 ***************************************************************************/

// This file is Auto Generated By CMake!! Don't edit it unless you're completely
// out of your goddamn mind!!

#ifndef CONFIG_AQPM_H
#define CONFIG_AQPM_H

/* Defines the Install Prefix */
#define INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"

/* Defines the Version */
#define AQPM_VERSION "${AQPM_VERSION_STRING}"

#define AQPM_CONFIGURATION_FILE "${AQPM_CONFIGURATION_FILE}"

/* KDE4 Integration */
#cmakedefine KDE4_INTEGRATION 1

#endif /*CONFIG_AQPM_H*/ 
